"""add_last_api_reset_date

Revision ID: c16b2791896f
Revises: e6bbb9763c52
Create Date: 2026-06-17 08:25:29.779578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c16b2791896f'
down_revision: Union[str, None] = 'e6bbb9763c52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_api_reset_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_api_reset_date')
    # ### end Alembic commands ###
