"""add_user_columns

Revision ID: e6bbb9763c52
Revises: 84c7ad905137
Create Date: 2026-06-17 07:52:05.582489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6bbb9763c52'
down_revision: Union[str, None] = '84c7ad905137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_requests', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('self_analysis_cooltime', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('self_analysis_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'self_analysis_date')
    op.drop_column('users', 'self_analysis_cooltime')
    op.drop_column('users', 'api_requests')
    # ### end Alembic commands ###
